// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQQdIObr1HnSMrmYggQWTIWwlGChs-_E',
    appId: '1:629337717277:web:f0f939571cd55a05e624f4',
    messagingSenderId: '629337717277',
    projectId: 'talacare-a1',
    authDomain: 'talacare-a1.firebaseapp.com',
    storageBucket: 'talacare-a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7xaUZNib8L9M7k6zhgu7RKqFuw5VPqg',
    appId: '1:629337717277:android:36fea2f151e08c9fe624f4',
    messagingSenderId: '629337717277',
    projectId: 'talacare-a1',
    storageBucket: 'talacare-a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXa9oY92yccjiYJZm0tprGSdUVwNZPv-g',
    appId: '1:629337717277:ios:deb02d120d8caee6e624f4',
    messagingSenderId: '629337717277',
    projectId: 'talacare-a1',
    storageBucket: 'talacare-a1.appspot.com',
    iosClientId: '629337717277-tbupo02afeuju8mvrd8fc67qfnkd35ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.talacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXa9oY92yccjiYJZm0tprGSdUVwNZPv-g',
    appId: '1:629337717277:ios:83cfc115f69ad6d0e624f4',
    messagingSenderId: '629337717277',
    projectId: 'talacare-a1',
    storageBucket: 'talacare-a1.appspot.com',
    iosClientId: '629337717277-k0uct9i97bbbgklvj223a77pvjq8poc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.talacare.RunnerTests',
  );
}
